<#include "common/ui/form.ftl"/>
<#include "common/ui/button.ftl"/>
<#include "common/ui/radio.ftl"/>
<#include "common/ui/radio_button.ftl"/>
<#include "common/ui/checkbox.ftl"/>
<#include "common/ui/checkbox_group.ftl"/>
<#include "common/ui/bit_checkbox.ftl"/>
<#include "common/ui/drop_down.ftl"/>
<#include "common/ui/drag_drop.ftl"/>
<#include "common/ui/tab.ftl"/>
<#include "common/ui/slide_tab.ftl"/>
<#include "common/ui/dynamic_tab.ftl"/>
<#include "common/ui/time_selection.ftl"/>
<#include "common/ui/panel.ftl"/>
<#include "common/ui/table.ftl"/>
<#include "common/ui/date_range_selector.ftl"/>
<#include "common/ui/date_pick.ftl"/>
<#include "common/ui/destination_selection.ftl"/>
